# Generated by Django 4.0.3 on 2022-03-24 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySpace_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('add_info', models.TextField()),
                ('response', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('grade', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rank',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='StudTakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz1_score', models.IntegerField(null=True)),
                ('quiz2_score', models.IntegerField(null=True)),
                ('midterm_score', models.IntegerField(null=True)),
                ('endterm_score', models.IntegerField(null=True)),
                ('assignment_score', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 24, 42, 813560))),
                ('cert_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.certreq')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudPartOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='SecCanRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.notice')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.notice')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='InstTeaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='InstReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 24, 42, 813560))),
                ('cert_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.certreq')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='InstPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 24, 42, 829139))),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.faculty')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.notice')),
            ],
        ),
        migrations.CreateModel(
            name='InstOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.section')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.dept'),
        ),
        migrations.CreateModel(
            name='AdminReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 24, 42, 829139))),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cert_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.certreq')),
            ],
        ),
        migrations.CreateModel(
            name='AdminPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 24, 42, 829139))),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.notice')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mySpace_app.dept'),
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mySpace_app.dept'),
        ),
        migrations.CreateModel(
            name='SemFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('tuition_fee', models.IntegerField(blank=True)),
                ('hostel_fee', models.IntegerField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('result', models.FileField(upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='MessFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('mess_fee', models.IntegerField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.student')),
            ],
            options={
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
