# Generated by Django 4.0.3 on 2022-03-29 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0003_alter_studtakes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 14, 31, 8, 482963)),
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 14, 31, 8, 482963)),
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 14, 31, 8, 483965)),
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 14, 31, 8, 481965)),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 14, 31, 8, 482963)),
        ),
    ]
