# Generated by Django 4.0.3 on 2022-03-31 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0008_alter_adminpublish_published_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfee',
            name='mess_fee_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='semfee',
            name='hostel_fee_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='semfee',
            name='tuition_fee_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 11, 43, 32, 198114)),
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 11, 43, 32, 197712)),
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 11, 43, 32, 198713)),
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 11, 43, 32, 196713)),
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 11, 43, 32, 197006)),
        ),
    ]
