# Generated by Django 4.0.3 on 2022-03-31 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0009_messfee_mess_fee_paid_semfee_hostel_fee_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 7, 57, 738424)),
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 7, 57, 737280)),
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 7, 57, 739528)),
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 7, 57, 736493)),
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 7, 57, 737280)),
        ),
        migrations.AlterField(
            model_name='studtakes',
            name='assignment_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studtakes',
            name='endterm_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studtakes',
            name='midterm_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studtakes',
            name='quiz1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studtakes',
            name='quiz2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
