# Generated by Django 4.0.3 on 2022-03-31 06:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mySpace_app', '0010_alter_adminpublish_published_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studtakes',
            options={},
        ),
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 13, 6, 252346)),
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 13, 6, 251346)),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 13, 6, 252346)),
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 13, 6, 251346)),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 13, 6, 251346)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='adminpublish',
            unique_together={('admin', 'notice')},
        ),
        migrations.AlterUniqueTogether(
            name='adminreview',
            unique_together={('admin', 'cert_req')},
        ),
        migrations.AlterUniqueTogether(
            name='instof',
            unique_together={('faculty', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='instpublish',
            unique_together={('faculty', 'notice')},
        ),
        migrations.AlterUniqueTogether(
            name='instreq',
            unique_together={('faculty', 'cert_req')},
        ),
        migrations.AlterUniqueTogether(
            name='instteaches',
            unique_together={('faculty', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='noticetag',
            unique_together={('notice', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='seccanread',
            unique_together={('section', 'notice')},
        ),
        migrations.AlterUniqueTogether(
            name='studpartof',
            unique_together={('student', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='studreq',
            unique_together={('student', 'cert_req')},
        ),
        migrations.AlterUniqueTogether(
            name='studtakes',
            unique_together={('student', 'course')},
        ),
    ]
