# Generated by Django 4.0.3 on 2022-03-31 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0012_alter_adminpublish_published_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 19, 27, 773932)),
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 19, 27, 773932)),
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 19, 27, 773932)),
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 19, 27, 772932)),
        ),
        migrations.AlterField(
            model_name='messfee',
            name='mess_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messfee',
            name='mess_fee_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semfee',
            name='hostel_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semfee',
            name='hostel_fee_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semfee',
            name='tuition_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semfee',
            name='tuition_fee_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 19, 27, 772932)),
        ),
    ]
