<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-06 09:50
=======
# Generated by Django 4.0.3 on 2022-04-07 08:13
>>>>>>> 6c8f2191f3b0c9910702f79542349f6c00392aa5

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0014_alter_adminpublish_published_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 15, 20, 48, 181749)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 43, 2, 965725)),
>>>>>>> 6c8f2191f3b0c9910702f79542349f6c00392aa5
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 15, 20, 48, 181749)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 43, 2, 964725)),
>>>>>>> 6c8f2191f3b0c9910702f79542349f6c00392aa5
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 15, 20, 48, 181749)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 43, 2, 965725)),
>>>>>>> 6c8f2191f3b0c9910702f79542349f6c00392aa5
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 15, 20, 48, 181749)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 43, 2, 964725)),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.FileField(upload_to='media/<django.db.models.fields.PositiveSmallIntegerField>/'),
>>>>>>> 6c8f2191f3b0c9910702f79542349f6c00392aa5
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 15, 20, 48, 181749)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 43, 2, 964725)),
>>>>>>> 6c8f2191f3b0c9910702f79542349f6c00392aa5
        ),
    ]
