# Generated by Django 4.0.3 on 2022-04-07 08:20

import datetime
from django.db import migrations, models
import mySpace_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0017_alter_adminpublish_published_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 50, 26, 783929)),
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 50, 26, 783929)),
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 50, 26, 783929)),
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 50, 26, 782933)),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.FileField(upload_to=mySpace_app.models.Result.semwise_upload_to),
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 13, 50, 26, 782933)),
        ),
    ]
