# Generated by Django 4.0.3 on 2022-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0022_alter_adminpublish_published_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpublish',
            name='published_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminreview',
            name='review_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instpublish',
            name='published_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instreq',
            name='req_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studreq',
            name='req_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
