# Generated by Django 4.0.3 on 2022-04-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0024_alter_result_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
