# Generated by Django 4.0.3 on 2022-04-07 09:11

from django.db import migrations, models
import mySpace_app.models
import mySpace_app.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0025_alter_dept_dept_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Class', 'Class-TimeTable'), ('Exam', 'ExamTimeTable')], default='Class', max_length=5)),
                ('schedule', models.FileField(max_length=30, storage=mySpace_app.storage.OverwriteStorage(), upload_to=mySpace_app.models.TimeTable.type_upload_to)),
            ],
        ),
    ]
