# Generated by Django 4.0.3 on 2022-04-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0028_alter_timetable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.IntegerField()),
                ('fine_paid', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySpace_app.student')),
            ],
        ),
    ]
