# Generated by Django 4.0.3 on 2022-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0032_alter_messfee_mess_fee_alter_semfee_hostel_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpublish',
            name='published_on',
        ),
        migrations.RemoveField(
            model_name='instpublish',
            name='published_on',
        ),
        migrations.RemoveField(
            model_name='instreq',
            name='req_date',
        ),
        migrations.RemoveField(
            model_name='studreq',
            name='req_date',
        ),
        migrations.AddField(
            model_name='certreq',
            name='req_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='published_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
