# Generated by Django 4.0.3 on 2022-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0033_remove_adminpublish_published_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certreq',
            name='response',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
