# Generated by Django 4.0.3 on 2022-04-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0036_coursedetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetails',
            options={'verbose_name_plural': 'CourseDetails'},
        ),
    ]
