# Generated by Django 4.0.3 on 2022-04-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySpace_app', '0038_alter_coursedetails_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
